### ISSUE TITLE
Add typescript type definitions

### ISSUE THREAD

**Issue by saeed-abdul-rahim** [Pik-9/schluessel#2] opened 2020-07-10 14:38 UTC
VS Code displays error:
Try `npm install @types/schluessel` if it exists or add a new declaration (.d.ts) file containing `declare module 'schluessel';`ts(7016)

**Comment by Pik-9** [comment] 2020-07-10 17:05
Hi @saeed-abdul-rahim,

the problem here is, that you are trying to use a Vanilla JavaScript package in your _typescript_ project. Then your typescript compiler is complaining, that it is lacking a _type definitions_ file.
The issue is explained here: https://stackoverflow.com/questions/46414740/how-to-use-untyped-js-npm-modules-in-typescript-for-node

The easiest suggested solution for you would be:
```typescript
import credentials = require('schluessel');
```

But I keep this issue open until I figured out, how to add these _type definitions_ to my package. I must admit that I have never worked with **typescript** before.

Regards
:nine::spades:

**Comment by Pik-9** [comment] 2020-07-13 00:07
## Update
I opened a [pull request on DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46045).
Then `@types/schluessel` will be available soon.

This issue will be closed once the PR is accepted.

**Comment by Pik-9** [comment] 2020-07-13 17:18
## Typescript support

Ok, It's done! :ok_hand: 
The type definitions are there and can be installed with:
```bash
npm i -D @types/schluessel
```

You can then use it in your TS project like this:
```typescript
import credentials = require('schluessel');
```

I will close this issue, now.

**Closed as completed by Pik-9** 2020-07-13 17:18 UTC
